const projectsData = [
  {
    "id": "branding1",
    "title": "Sakab Sport",
    "category": "Branding",
    "country": "KSA",
    "client": "Sport",
    "industry": "Branding",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Sakab%20Sport/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Sakab%20Sport/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Sakab%20Sport/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Sakab%20Sport/4.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Sakab%20Sport/5.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Sakab%20Sport/6.png"],
    "video": "",
  },
  {
    "id": "branding2",
    "title": "Cammoun",
    "category": "Branding",
    "country": "KSA",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Cammoun/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Cammoun/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Cammoun/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Cammoun/4.png"
    ],
    "video": ""
  },
  {
    "id": "branding3",
    "title": "Babel Ltd.",
    "category": "Branding",
    "country": "UAE / EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Babel%20Ltd/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Babel%20Ltd/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Babel%20Ltd/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Babel%20Ltd/4.png",
    ],
    "video": ""
  },
  {
    "id": "branding5",
    "title": "NMG",
    "category": "Branding",
    "country": "USA / KSA",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/NMG/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/NMG/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/NMG/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/NMG/4.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/NMG/5.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/NMG/6.png",
    ],
    "video": ""
  },
  {
    "id": "branding6",
    "title": "Cairo Bites",
    "category": "Branding",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Cairo%20Bites/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Cairo%20Bites/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Cairo%20Bites/3.png",
    ],
    "video": ""
  },
  {
    "id": "branding7",
    "title": "Sohi wa Sarih",
    "category": "Branding",
    "country": "Lebanon",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Sohi%20wa%20Sarih/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Sohi%20wa%20Sarih/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Sohi%20wa%20Sarih/3.png"
    ],
    "video": ""
  },
  {
    "id": "branding8",
    "title": "Liqua lites",
    "category": "Branding",
    "country": "UK",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Liqua%20lites/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Liqua%20lites/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Liqua%20lites/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Liqua%20lites/4.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Liqua%20lites/5.png",
    ],
    "video": ""
  },
  {
    "id": "branding9",
    "title": "APEX",
    "category": "Branding",
    "country": "UAE/UK",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/APEX/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/APEX/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/APEX/3.png"
    ],
    "video": ""
  },
  {
    "id": "branding10",
    "title": "Sasco",
    "category": "Branding",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Sasco/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Sasco/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Sasco/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Sasco/4.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Sasco/5.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Sasco/6.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Sasco/7.png",
    ],
    "video": ""
  },
  {
    "id": "branding11",
    "title": "Sehet Moustakbalna",
    "category": "Branding",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Sehet%20Moustakbalna/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Sehet%20Moustakbalna/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Sehet%20Moustakbalna/3.png",
    ],
    "video": ""
  },
  {
    "id": "branding12",
    "title": "Eastlands International School",
    "category": "Branding",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Eastlands%20International%20School/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Eastlands%20International%20School/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Eastlands%20International%20School/Asset%2048.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Eastlands%20International%20School/Asset%2049.png",
    ],
    "video": ""
  },
  {
    "id": "branding13",
    "title": "The Child Expo",
    "category": "Branding",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Child%20Expo/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Child%20Expo/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Child%20Expo/3.png"
    ],
    "video": ""
  },
  {
    "id": "branding14",
    "title": "Money Talks",
    "category": "Branding",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Money%20Talks/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Money%20Talks/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Money%20Talks/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Money%20Talks/4.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Money%20Talks/5.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Money%20Talks/6.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Money%20Talks/7.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Money%20Talks/8.png"
    ],
    "video": ""
  },
  {
    "id": "branding15",
    "title": "Oxford Modern School",
    "category": "Branding",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Oxford%20Modern%20School/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Oxford%20Modern%20School/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Oxford%20Modern%20School/3.png"
    ],
    "video": ""
  },
  {
    "id": "branding16",
    "title": "MAY University in Cairo",
    "category": "Branding",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/MAY%20University%20in%20Cairo/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/MAY%20University%20in%20Cairo/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/MAY%20University%20in%20Cairo/3.png"
    ],
    "video": ""
  },
  {
    "id": "branding17",
    "title": "Enzymax Billboards",
    "category": "Branding",
    "country": "KSA",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Enzymax%20Billboards/1.png",
    "hasVideo": false,
    "description": "Developed a master visual identity and communication concept that brought the brand's narrative to life. The result was a flexible visual system that could be applied across product packaging, digital assets, and in-store displays, establishing a strong, recognizable presence for Liblab in a competitive market.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "branding18",
    "title": "Liblab Visuals",
    "category": "Branding",
    "country": "KSA",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Liblab%20Visuals/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Liblab%20Visuals/2.png"
    ],
    "video": ""
  },
  {
    "id": "branding19",
    "title": "Savy Shelf Talker",
    "category": "Branding",
    "country": "KSA",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "branding20",
    "title": "Lorinase D Stand",
    "category": "Branding",
    "country": "KSA",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Lorinase%20D%20Stand/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Lorinase%20D%20Stand/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Branding/Lorinase%20D%20Stand/3.png"
    ],
    "video": ""
  },
  {
    "id": "conceptsproduction1",
    "title": "Fevadol Campaign Concept",
    "category": "Concepts & Production",
    "country": "KSA",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Fevadol%20Campaign%20Concept/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Fevadol%20Campaign%20Concept/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Fevadol%20Campaign%20Concept/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Fevadol%20Campaign%20Concept/4.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Fevadol%20Campaign%20Concept/5.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Fevadol%20Campaign%20Concept/6.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Fevadol%20Campaign%20Concept/7.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Fevadol%20Campaign%20Concept/8.png"
    ],
    "video": ""
  },
  {
    "id": "conceptsproduction2",
    "title": "Peptazol Visual and Nahdi Campaign Designs",
    "category": "Concepts & Production",
    "country": "KSA",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Peptazol%20Visual%20and%20Nahdi%20Campaign%20Designs/1.png",
    "hasVideo": false,
    "description": "Peptazol is a widely used treatment for acid reflux, ulcers, and heartburn in Saudi Arabia. It contains lansoprazole and is taken once daily before meals to reduce stomach acid and improve digestive comfort.",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Peptazol%20Visual%20and%20Nahdi%20Campaign%20Designs/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Peptazol%20Visual%20and%20Nahdi%20Campaign%20Designs/3.png"
    ],
    "video": ""
  },
  {
    "id": "conceptsproduction3",
    "title": "Enzymax & Peptazol Counter Stand",
    "category": "Concepts & Production",
    "country": "KSA",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Enzymax/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Enzymax/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Enzymax/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Enzymax/4.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Enzymax/5.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Enzymax/6.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Enzymax/7.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Enzymax/8.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Enzymax/9.png",
    ],
    "video": ""
  },
  {
    "id": "conceptsproduction4",
    "title": "Abbott Nutrition Office Branding",
    "category": "Concepts & Production",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Abbott%20Office%20Branding/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Abbott%20Office%20Branding/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Abbott%20Office%20Branding/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Abbott%20Office%20Branding/4.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Abbott%20Office%20Branding/5.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Abbott%20Office%20Branding/6.png",
    ],
    "video": ""
  },
  {
    "id": "conceptsproduction5",
    "title": "MUC University Booth Design & Production",
    "category": "Concepts & Production",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/MUC%20University%20Booth%20Design%20&%20Production/1.png",
    "hasVideo": false,
    "description": "May University in Cairo is a private university located in 15 May City, offering accredited programs in engineering, business, and physical therapy. With modern facilities and a smart campus environment, MUC emphasizes hands-on learning and global academic standards.",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/MUC%20University%20Booth%20Design%20&%20Production/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/MUC%20University%20Booth%20Design%20&%20Production/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/MUC%20University%20Booth%20Design%20&%20Production/4.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/MUC%20University%20Booth%20Design%20&%20Production/5.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/MUC%20University%20Booth%20Design%20&%20Production/6.png",
    ],
    "video": ""
  },
  {
    "id": "conceptsproduction6",
    "title": "Maalox Control Booth Design & Production",
    "category": "Concepts & Production",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Maalox%20Control%20Booth%20Design%20&%20Production/1.png",
    "hasVideo": false,
    "description": "Maalox Control is an over-the-counter solution for acid reflux and heartburn, providing fast relief by reducing stomach acid. It’s taken once daily and is known for being effective, accessible, and easy to use.",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Maalox%20Control%20Booth%20Design%20&%20Production/2.png",
    ],
    "video": ""
  },
  {
    "id": "conceptsproduction7",
    "title": "Sanofi Office Branding",
    "category": "Concepts & Production",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Sanofi%20Office%20Branding/1.png",
    "hasVideo": false,
    "description": "Sanofi transformed its Egypt office to reflect a more modern, collaborative, and commercial identity, moving away from traditional pharmaceutical branding. The new space aligns with the company’s global direction, focusing on openness, agility, and employee well-being.",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Sanofi%20Office%20Branding/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Sanofi%20Office%20Branding/3.png"
    ],
    "video": ""
  },
  {
    "id": "conceptsproduction8",
    "title": "Enterogermina Booth Design & Production",
    "category": "Concepts & Production",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Enterogermina%20Booth%20Design%20&%20Production/1.png",
    "hasVideo": false,
    "description": "Designed and produced a custom booth for Enterogermina, tailored to reflect its probiotic positioning and family-friendly identity. The booth featured interactive zones and clean, clinical visuals, helping the brand connect with both healthcare professionals and general consumers.",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Enterogermina%20Booth%20Design%20&%20Production/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Enterogermina%20Booth%20Design%20&%20Production/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Enterogermina%20Booth%20Design%20&%20Production/4.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Enterogermina%20Booth%20Design%20&%20Production/5.png",
    ],
    "video": ""
  },
  {
    "id": "conceptsproduction9",
    "title": "Liblab Visuals",
    "category": "Concepts & Production",
    "country": "KSA",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Liblab%20Visuals/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Liblab%20Visuals/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Liblab%20Visuals/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Liblab%20Visuals/4.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Liblab%20Visuals/5.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Liblab%20Visuals/6.png",
    ],
    "video": ""
  },
  {
    "id": "conceptsproduction10",
    "title": "Talabat insomnia Booth",
    "category": "Concepts & Production",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Talabat%20Insomnia/1.png",
    "hasVideo": false,
    "description": "We created a fully branded booth for Talabat that showcased the platform’s speed, convenience, and tech-driven identity. helping Talabat engage directly with diverse audiences. Strategically positioned at key events, the booth featured touchscreens, giveaways, and playful visuals that captured the essence of the Talabat experience—modern, fun, and reliable.",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Talabat%20Insomnia/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Talabat%20Insomnia/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Talabat%20Insomnia/4.jpeg",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Talabat%20Insomnia/5.jpeg",
    ],
    "video": ""
  },
  {
    "id": "conceptsproduction11",
    "title": "Talabat Sustainability Booth",
    "category": "Concepts & Production",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Talabat%20Sustainability/1.png",
    "hasVideo": false,
    "description": "We created a fully branded booth for Talabat that showcased the platform’s speed, convenience, and tech-driven identity. helping Talabat engage directly with diverse audiences. Strategically positioned at key events, the booth featured touchscreens, giveaways, and playful visuals that captured the essence of the Talabat experience—modern, fun, and reliable.",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Talabat%20Sustainability/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Talabat%20Sustainability/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Talabat%20Sustainability/4.jpg",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Talabat%20Sustainability/5.jpg",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Talabat%20Sustainability/6.jpg",
    ],
    "video": ""
  },
  {
    "id": "conceptsproduction13",
    "title": "Natural Birth Campaign Concept",
    "category": "Concepts & Production",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Natural%20Birth%20Campaign/1.png",
    "hasVideo": false,
    "description": "We partnered with Egypt’s Ministry of Health to launch a Natural Birth Awareness Campaign aimed at educating expectant mothers on the benefits and safety of natural delivery. The campaign’s tone was supportive, factual, and empowering, dispelling myths and promoting informed choices. Our work included digital content, medical endorsements, and on-ground activations in hospitals and clinics—creating a multi-touchpoint experience that prioritized maternal health and national health goals.",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Natural%20Birth%20Campaign/2.png",
    ],
    "video": ""
  },
  {
    "id": "conceptsproduction15",
    "title": "Enterogermina Karl Beach Booth",
    "category": "Concepts & Production",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Entrogermina%20Karl%20Beach/1.jpg",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Entrogermina%20Karl%20Beach/2.jpg",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Entrogermina%20Karl%20Beach/3.jpg",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Entrogermina%20Karl%20Beach/4.jpg",
    ],
    "video": ""
  },
  {
    "id": "conceptsproduction17",
    "title": "Telfast Bikes Alex event",
    "category": "Concepts & Production",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Telfast%20Bikes%20Alex%20event/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Telfast%20Bikes%20Alex%20event/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Telfast%20Bikes%20Alex%20event/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Telfast%20Bikes%20Alex%20event/4.png",
    ],
    "video": ""
  },
  {
    "id": "conceptsproduction18",
    "title": "Spimaco Stand",
    "category": "Concepts & Production",
    "country": "KSA",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Spimaco/1.jpg",
    "hasVideo": false,
    "description": "Developed branded pharmacy stands for SPIMACO to enhance on-shelf visibility and point-of-sale engagement across key retail locations. The design was clean, informative, and aligned with SPIMACO’s professional pharmaceutical image. Built for durability and flexibility, the stands served as a high-impact retail tool, increasing product awareness while maintaining medical credibility in both chain and independent pharmacies.",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Spimaco/2.jpg",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Spimaco/3.jpg",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Spimaco/4.jpg",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Spimaco/5.jpg"
    ],
    "video": ""
  },
  {
    "id": "conceptsproduction19",
    "title": "Haleon Be Proactive",
    "category": "Concepts & Production",
    "country": "KSA",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Haleon%20Be%20Proactive/1.jpg",
    "hasVideo": false,
    "description": "For Sensodyne, we rolled out an awareness campaign focused on educating the public about dentine hypersensitivity and its impact on daily life. The tone was both informative and reassuring, driving home the importance of proper oral care.",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Haleon%20Be%20Proactive/2.jpg",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Haleon%20Be%20Proactive/3.jpg",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Concepts/Haleon%20Be%20Proactive/4.jpg",
    ],
    "video": ""
  },
  {
    "id": "endtoendeventorganization1",
    "title": "Enterogermina 4 Billion Launch Event",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "In the world of Enterogermina. the city's power comes from the laughter of the family. However, they're not laughing as much due to digestive issues. The Enterogermina characters offer children Enterogermina 4 Billion probiotics, restoring balance to their gut and making them happy. By promoting digestive health and happiness, the Enterogermina characters make a positive impact on the lives of children and families.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization33",
    "title": "Enterogermina 2 Billion Launch Event",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Events/Enterogermina%204%20Billion%20Launch%20Event/1.JPG",
    "hasVideo": true,
    "description": "In the world of Enterogermina. the city's power comes from the laughter of the family. However, they're not laughing as much due to digestive issues. The Enterogermina characters offer children Enterogermina 4 Billion probiotics, restoring balance to their gut and making them happy. By promoting digestive health and happiness, the Enterogermina characters make a positive impact on the lives of children and families.",
    "slideshow": [],
    "video": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/Videos/Enterogermina%202%20Billion%20Launch%20Event.mp4"
  },
  {
    "id": "endtoendeventorganization2",
    "title": "Pedia Academy 2022",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "The concept of the event is the seven precious stones Each stone represents one of the seven gems of pediatrics products from Sanofi which are allergy, cough, anti-inflammatory, digestive health, antibiotics, antidiabetes and vaccines. Sanofi pedia academy Sanofi pedia academy combines all the gems, for healthy & happy children, in all seasons, all year, guaranteed by the pediatric expertise of Sanofi.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization3",
    "title": "Art Cairo 2023",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "Founded in March 2020, amid the first wave of the global COVID19- pandemic, Egypt International Art Fair has overcome many challenges. The first edition featured works by more than 100 artists with a total participation of around 1300 artworks by 18 participating galleries from Egypt and the MENA region. The second edition, in February 2021, featured more than 20 galleries from across the region with a complimentary program of events, talks and studio events. Alongside the galleries was a curated section displaying established and prominent artists from Egypt and abroad.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization4",
    "title": "1001 Nights Mustela Event",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "Meet exclusively our expert “Mustela Champions” and get ready for a spectacular night full of fun & entertainment for you and your kids and enjoy many more exciting activities. for the very first time in Egypt, to attend Mustela Mega Event One thousand and one nights!",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization5",
    "title": "Essentiale Launch Event",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "Essentiale is world no.1 liver care productAwareness about both NAFLD & MAFLD and its implications on health are very low. Sufferers do not acknowledge they have liver conditions because Liver is silentOur Main Focus Message is” 3 actions for liver care. Stabilize, protects and regenerates",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization6",
    "title": "Social Inclusion Campaign Launch",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "from the launch event today of the #DiverseButUnited campaign and the latest song of Donia Samir Ghanem, UNICEF Ambassador in Egypt, on children's equal rights despite their diversities. This campaign is supported by the PROSPECTS programme – a partnership between the Embassy of the Netherlands in Egypt, IFC, ILO, UNHCR Egypt and UNICEF. In partnership with UNICEF, we supported the launch of a Social Inclusion Campaign aimed at promoting equity and diversity among youth. The event highlighted stories of inclusion, resilience, and hope, reinforcing UNICEF’s humanitarian mission.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization7",
    "title": "Sanofi Cycle Meeting 2022",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "Achieving success is never an easy task, it takes a lot of dedication, respect, commitment and most importantly, the Teamwork. Sanofi has always been, and always will be, an ambitious company, striving for excellence, to accomplish what can only be described as glory and greatness, and this cannot be achieved without the power of its staff, without The Power of We…",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization8",
    "title": "The Child Expo",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "EGYPT'S BIGGEST CHILD EVENT The most loved event by both parents & children",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization9",
    "title": "Cairo Bites",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "Cairo Bites is Egypt's first & biggest food festival featuring a wide and diversified line-up of local, regional as well as international eating establishments and food-related businesses in a fun, warm and dynamic environment identified as the ultimate showcase of the Egyptian food industry.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization10",
    "title": "Grow Happy",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "Grow Happy is an event crafted around the idea of raising awareness for children and moms",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization11",
    "title": "Abbott Nutrition Events",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization12",
    "title": "The Art Week",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "The Art Week is a Unique Art experience powered by Azad gallery.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization13",
    "title": "Art Cairo 2024",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "Founded in March 2020, amid the first wave of the global COVID19- pandemic, Egypt International Art Fair has overcome many challenges. The first edition featured works by more than 100 artists with a total participation of around 1300 artworks by 18 participating galleries from Egypt and the MENA region. The second edition, in February 2021, featured more than 20 galleries from across the region with a complimentary program of events, talks and studio events. Alongside the galleries was a curated section displaying established and prominent artists from Egypt and abroad.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization14",
    "title": "The Art Week 2024",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "The Art Week is a Unique Art experience powered by Azad gallery.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization15",
    "title": "Bites by the sea",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization16",
    "title": "Opella Soft Launch",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "Executed the soft launch of Opella, marking its strategic transition from Sanofi’s consumer healthcare division into a standalone commercial entity. The event introduced the new brand identity while honoring the legacy and values of its parent company.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization17",
    "title": "Sanofi Brand & Innovation Kick Off Meeting",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "The concept of the event is the seven precious stones Each stone represents one of the seven gems of pediatrics products from Sanofi which are allergy, cough, anti-inflammatory, digestive health, antibiotics, antidiabetes and vaccines. Sanofi pedia academy Sanofi pedia academy combines all the gems, for healthy & happy children, in all seasons, all year, guaranteed by the pediatric expertise of Sanofi. We organized Sanofi’s Brand & Innovation Kick-off Meeting, bringing together key teams to align on strategic goals, creative thinking, and upcoming product innovations. The event emphasized collaboration, agility, and brand evolution.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization18",
    "title": "Opella Cycle Meeting 2024",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "The Opella Company Cycle Meeting brought teams together to align on performance updates, future plans, and strategic market priorities. The event featured engaging presentations, branded visuals, and dynamic breakout sessions that reflected Opella’s energetic, consumer-driven spirit.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization19",
    "title": "Buscopan HCP Meetings",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "A series of Buscopan medical meetings was held across Ras El Barr, Alexandria, and Cairo, targeting healthcare professionals with a focus on abdominal pain management and clinical efficacy. The format combined scientific content, peer interaction, and brand storytelling in a relaxed, professional environment.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization20",
    "title": "Sanofi Accelerate Africa",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "The Accelerate Africa Meeting marked the first in-person gathering of Sanofi’s Africa leadership teams, fostering alignment across countries and business units. The experience blended strategic workshops, leadership talks, and cultural exchange in a dynamic, cross-continental setting.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization21",
    "title": "Opella Purpose Day",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "Purpose Day was an environmental awareness activation hosted by Opella at a local school, designed to educate children about sustainability through fun and interactive experiences. The day featured workshops, planting, and branded giveaways that tied into Opella’s purpose-led identity.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization22",
    "title": "Pedia Academy",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "Pedia Academy was an educational event dedicated to Opella’s pediatric portfolio, bringing together healthcare professionals to explore product insights, clinical updates, and patient engagement tools. The setting encouraged discussion and cross-learning across multiple pediatric disciplines.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization24",
    "title": "Opella New Office Opening",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "A tailored celebration marked Opella’s relocation to its new premises at U Venues. The event featured a welcoming atmosphere for employees, customized installations, and interactive elements that showcased Opella’s identity and future direction.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization25",
    "title": "Art Cairo 2025",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization26",
    "title": "Sanofi Cycle Meeting",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "A strategic full-company gathering to kick off a new business cycle for Sanofi, bringing together employees from different divisions for workshops, plenary sessions, and team-building activities. The event aligned internal teams on priorities, reenergized staff, and delivered Sanofi’s vision for the coming months through a balanced mix of inspiration and operational focus.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization27",
    "title": "Sanofi Finance Kick OFF",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "A focused internal event for Sanofi’s finance department, built around strategic planning, cross-functional discussions, and performance alignment. Held in a motivating setting with branded materials and curated sessions.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization28",
    "title": "Telfast Pharamacists Event",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "An engagement event designed exclusively for pharmacists, introducing them to Telfast’s key differentiators and treatment benefits. The setup included an informative booth, branded giveaways, and interactive knowledge-based activities.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization29",
    "title": "Opella Day 1 Event",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "A day-one activation to welcome employees into Opella’s new office, complete with welcoming visuals, refreshments, and branded onboarding elements. The experience made the first day memorable and energizing, helping staff settle in while reinforcing Opella’s brand culture and values.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization30",
    "title": "Opella Connect",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "A dedicated pharmacists engagement event featuring all of Opella’s OTC portfolio, designed to educate, engage, and build brand familiarity through booth activations, product showcases, and interactive presentations. The event solidified pharmacists’ trust in Opella products and created a direct line of communication between the brand and its retail partners.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization31",
    "title": "Telfast No-Brainer",
    "category": "End to end Event Organization",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "A themed event targeting healthcare professionals to highlight Telfast’s standout benefits in allergy relief, focusing on the product’s non-drowsy formula. The concept “No Brainer” was creatively brought to life through branded setups and interactive content.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "endtoendeventorganization32",
    "title": "Opella AMET Event",
    "category": "End to end Event Organization",
    "country": "Turkey",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "A multinational gathering for Opella’s AMET regional team hosted in Turkey. The event combined business presentations with cultural and bonding experiences to strengthen inter-market collaboration. The gathering enhanced alignment across markets, built morale, and fostered a cohesive regional identity under the Opella umbrella.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "ongroundactivations1",
    "title": "Bronchicum Campaign 2022",
    "category": "On Ground Activations",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Bronchicum%20Campaign%202022/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Bronchicum%20Campaign%202022/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Bronchicum%20Campaign%202022/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Bronchicum%20Campaign%202022/4.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Bronchicum%20Campaign%202022/5.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Bronchicum%20Campaign%202022/6.png",
    ],
    "video": ""
  },
  {
    "id": "ongroundactivations2",
    "title": "Bronchicum Campaign 2023",
    "category": "On Ground Activations",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Bronchicum%20Campaign%202023/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Bronchicum%20Campaign%202023/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Bronchicum%20Campaign%202023/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Bronchicum%20Campaign%202023/4.png",
    ],
    "video": ""
  },
  {
    "id": "ongroundactivations3",
    "title": "Maalox in Cairobites 2022",
    "category": "On Ground Activations",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Maalox%20CairoBites/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Maalox%20CairoBites/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Maalox%20CairoBites/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Maalox%20CairoBites/4.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Maalox%20CairoBites/5.png",
    ],
    "video": ""
  },
  {
    "id": "ongroundactivations4",
    "title": "Maalox Ramadan 2022",
    "category": "On Ground Activations",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Maalox%20Ramadan/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Maalox%20Ramadan/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Maalox%20Ramadan/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Maalox%20Ramadan/4.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Maalox%20Ramadan/5.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Maalox%20Ramadan/6.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Maalox%20Ramadan/7.png",
    ],
    "video": ""
  },
  {
    "id": "ongroundactivations5",
    "title": "Maalox Ramadan 2023",
    "category": "On Ground Activations",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Maalox%20Ramadan/2.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "ongroundactivations6",
    "title": "Pedialyte Clubs Campaign 2021",
    "category": "On Ground Activations",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Pediasure/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Pediasure/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Pediasure/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Pediasure/4.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Pediasure/5.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Pediasure/6.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Pediasure/7.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Pediasure/8.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Pediasure/9.png",
    ],
    "video": ""
  },
  {
    "id": "ongroundactivations7",
    "title": "Pediasure Malls Activation 2021",
    "category": "On Ground Activations",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "Abbott Nutrition is a global leader in science-based health and nutrition, offering trusted brands like Similac, Ensure, Glucerna, and PediaSure. PediaSure is specially formulated to support healthy growth and immunity in children, especially those with picky appetites or nutritional gaps.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "ongroundactivations8",
    "title": "Pediasure Ramadan Campaign 2022",
    "category": "On Ground Activations",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "Abbott Nutrition is a global leader in science-based health and nutrition, offering trusted brands like Similac, Ensure, Glucerna, and PediaSure. PediaSure is specially formulated to support healthy growth and immunity in children, especially those with picky appetites or nutritional gaps.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "ongroundactivations9",
    "title": "Pediasure North Coast Campaign 2022",
    "category": "On Ground Activations",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "",
    "hasVideo": false,
    "description": "Abbott Nutrition is a global leader in science-based health and nutrition, offering trusted brands like Similac, Ensure, Glucerna, and PediaSure. PediaSure is specially formulated to support healthy growth and immunity in children, especially those with picky appetites or nutritional gaps.",
    "slideshow": [],
    "video": ""
  },
  {
    "id": "ongroundactivations10",
    "title": "Vacsera Campaign 2021",
    "category": "On Ground Activations",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Vacsera%202021/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Vacsera%202021/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Vacsera%202021/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Vacsera%202021/4.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Vacsera%202021/5.png",
    ],
    "video": ""
  },
  {
    "id": "ongroundactivations11",
    "title": "Moms Connect Program",
    "category": "On Ground Activations",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Moms%20Connect%20Program/1.png",
    "hasVideo": false,
    "description": "An ongoing initiative across clinics and hospitals, bringing mothers together for educational sessions led by pediatricians on gut health and wellness, with giveaways and child-focused activities.",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Moms%20Connect%20Program/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Moms%20Connect%20Program/3.png",
    ],
    "video": ""
  },
  {
    "id": "ongroundactivations12",
    "title": "Enterogermina Game",
    "category": "On Ground Activations",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Entrogermina%20Game/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Entrogermina%20Game/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Entrogermina%20Game/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Entrogermina%20Game/4.png",
    ],
    "video": ""
  },
  {
    "id": "ongroundactivations13",
    "title": "Enterogermina Campaign",
    "category": "On Ground Activations",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Entrogermina%20Campaign/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Entrogermina%20Campaign/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Entrogermina%20Campaign/3.png",
    ],
    "video": ""
  },
  {
    "id": "ongroundactivations14",
    "title": "Maalox Summer 2024 (Roadshow)",
    "category": "On Ground Activations",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Maalox%20Roadshow/1.png",
    "hasVideo": false,
    "description": "A mobile activation designed to engage consumers in key high-traffic locations, using a branded Dodge Ram vehicle and interactive booth elements to promote Maalox as a fast-acting solution for digestive discomfort.",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Maalox%20Roadshow/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Maalox%20Roadshow/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Maalox%20Roadshow/4.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Maalox%20Roadshow/5.png",
    ],
    "video": ""
  },
  {
    "id": "ongroundactivations15",
    "title": "Bronchicum Campaign 2023 (Roadshow)",
    "category": "On Ground Activations",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Bronchicum%20Roadshow/1.png",
    "hasVideo": false,
    "description": "An on-ground awareness campaign highlighting Bronchicum’s natural formula for treating cough and throat irritation. The branded setup toured across major cities, inviting consumers to experience the product and learn about its herbal composition.",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Bronchicum%20Roadshow/2.png",
    ],
    "video": ""
  },
  {
    "id": "ongroundactivations16",
    "title": "Talabat Schools Campaign",
    "category": "On Ground Activations",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Talabat%20School%20Campaign/1.png",
    "hasVideo": false,
    "description": "A multi-school activation that brought Talabat into students’ daily lives through engaging activities, and giveaways tailored for both students and parents during the back-to-school season.",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Talabat%20School%20Campaign/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Talabat%20School%20Campaign/3.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Talabat%20School%20Campaign/4.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Talabat%20School%20Campaign/5.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Talabat%20School%20Campaign/6.png",
    ],
    "video": ""
  },
  {
    "id": "ongroundactivations17",
    "title": "Enterogermina Vending Machine",
    "category": "On Ground Activations",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Entrogermina%20Vending%20Machine/1.png",
    "hasVideo": false,
    "description": "",
    "slideshow": [
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Entrogermina%20Vending%20Machine/2.png",
      "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Entrogermina%20Vending%20Machine/3.png",
    ],
    "video": ""
  },
  {
    "id": "ongroundactivations18",
    "title": "Enterogermina Carnaval",
    "category": "On Ground Activations",
    "country": "EGY",
    "client": "",
    "industry": "",
    "rate": "",
    "date": "",
    "thumbnail": "https://raw.githubusercontent.com/Sirkil/Sirkil_Website_Media/main/On%20Ground%20Activitions/Entrogermina%20Carnaval/1.jpg",
    "hasVideo": false,
    "description": "",
    "slideshow": [],
    "video": ""
  }
];
